[package]
name = "terminal"
version = "0.1.0"
edition = "2021"
description = "A terminal emulator and shell for Pomelo OS running on WebAssembly"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pomelo-sdk = { path = "../../../pomelo-sdk" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
