//! build.rs for app-launcher:
//! Automatically scans `assets/icons/*.png` at build time, resizes them to 56x56
//! using high-quality Lanczos3 resampling, and bakes them into hardware-native
//! RGB565 + 8-bit Alpha static arrays.

use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};

const ICON_SIZE: u32 = 56;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let icons_dir = manifest_dir.join("../../assets/icons");

    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let dest_path = out_dir.join("baked_icons.rs");
    let mut out_file = File::create(&dest_path).expect("failed to create baked_icons.rs");

    writeln!(out_file, "// Auto-generated by build.rs. Do not edit.\n").unwrap();
    writeln!(out_file, "#[allow(dead_code)]\npub mod baked {{").unwrap();
    writeln!(out_file, "    use pomelo_widgets::BitmapIcon;\n").unwrap();

    if icons_dir.exists() && icons_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(&icons_dir) {
            let mut entries: Vec<_> = entries.filter_map(Result::ok).collect();
            entries.sort_by_key(|e| e.path());

            for entry in entries {
                let path = entry.path();
                if path.is_file()
                    && path
                        .extension()
                        .and_then(|ext| ext.to_str())
                        .map(|ext| ext.eq_ignore_ascii_case("png"))
                        .unwrap_or(false)
                {
                    println!("cargo:rerun-if-changed={}", path.display());
                    let stem = path
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .unwrap_or("icon")
                        .replace(['-', ' ', '.'], "_");
                    let ident = stem.to_ascii_uppercase();

                    if let Err(e) = bake_icon(&path, &ident, &mut out_file) {
                        eprintln!("cargo:warning=Failed to bake icon {}: {}", path.display(), e);
                    }
                }
            }
        }
    }

    writeln!(out_file, "}}").unwrap();
}

fn bake_icon(path: &Path, ident: &str, out: &mut File) -> Result<(), Box<dyn std::error::Error>> {
    let img = image::open(path)?;
    let rgba = img.to_rgba8();
    let (w, h) = rgba.dimensions();

    // Center square crop
    let crop_size = w.min(h);
    let x_offset = (w - crop_size) / 2;
    let y_offset = (h - crop_size) / 2;

    let cropped = image::imageops::crop_imm(&rgba, x_offset, y_offset, crop_size, crop_size).to_image();

    // High quality Lanczos3 resize to 56x56
    let resized = image::imageops::resize(
        &cropped,
        ICON_SIZE,
        ICON_SIZE,
        image::imageops::FilterType::Lanczos3,
    );

    let total_pixels = (ICON_SIZE * ICON_SIZE) as usize;
    let mut rgb565_array = Vec::with_capacity(total_pixels);
    let mut alpha_array = Vec::with_capacity(total_pixels);

    for pixel in resized.pixels() {
        let r = pixel[0] as u16;
        let g = pixel[1] as u16;
        let b = pixel[2] as u16;
        let a = pixel[3];

        let r5 = (r >> 3) & 0x1F;
        let g6 = (g >> 2) & 0x3F;
        let b5 = (b >> 3) & 0x1F;
        let rgb = (r5 << 11) | (g6 << 5) | b5;

        rgb565_array.push(rgb);
        alpha_array.push(a);
    }

    // Write Rust static arrays
    writeln!(out, "    pub static {}_RGB: [u16; {}] = [", ident, total_pixels)?;
    for chunk in rgb565_array.chunks(16) {
        write!(out, "       ")?;
        for val in chunk {
            write!(out, " 0x{:04X},", val)?;
        }
        writeln!(out)?;
    }
    writeln!(out, "    ];\n")?;

    writeln!(out, "    pub static {}_ALPHA: [u8; {}] = [", ident, total_pixels)?;
    for chunk in alpha_array.chunks(24) {
        write!(out, "       ")?;
        for val in chunk {
            write!(out, " 0x{:02X},", val)?;
        }
        writeln!(out)?;
    }
    writeln!(out, "    ];\n")?;

    writeln!(
        out,
        "    pub static {}_ICON: BitmapIcon = BitmapIcon {{",
        ident
    )?;
    writeln!(out, "        width: {},", ICON_SIZE)?;
    writeln!(out, "        height: {},", ICON_SIZE)?;
    writeln!(out, "        rgb565: &{}_RGB,", ident)?;
    writeln!(out, "        alpha: &{}_ALPHA,", ident)?;
    writeln!(out, "    }};\n")?;

    Ok(())
}
