//! build.rs for app-launcher:
//! Automatically scans `assets/app-icons/*.png` at build time, resizes them to 56x56
//! using high-quality Lanczos3 resampling, applies an iOS-style squircle alpha mask,
//! and bakes them into hardware-native RGB565 + 8-bit Alpha static arrays.

use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};

const ICON_SIZE: u32 = 118;

/// iOS continuous-curvature squircle corner radius as a fraction of the icon size.
/// Apple uses ~22.5% of the side length.
const SQUIRCLE_RADIUS_RATIO: f32 = 0.225;


fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let icons_dir = manifest_dir.join("../../assets/app-icons");

    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let dest_path = out_dir.join("baked_icons.rs");
    let mut out_file = File::create(&dest_path).expect("failed to create baked_icons.rs");

    writeln!(out_file, "// Auto-generated by build.rs. Do not edit.\n").unwrap();
    writeln!(out_file, "#[allow(dead_code)]\npub mod baked {{").unwrap();
    writeln!(out_file, "    use pomelo_widgets::BitmapIcon;\n").unwrap();

    // Pre-compute the squircle mask once for all icons (same size).
    let squircle_mask = generate_squircle_mask(ICON_SIZE);

    if icons_dir.exists() && icons_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(&icons_dir) {
            let mut entries: Vec<_> = entries.filter_map(Result::ok).collect();
            entries.sort_by_key(|e| e.path());

            for entry in entries {
                let path = entry.path();
                if path.is_file()
                    && path
                        .extension()
                        .and_then(|ext| ext.to_str())
                        .map(|ext| ext.eq_ignore_ascii_case("png"))
                        .unwrap_or(false)
                {
                    println!("cargo:rerun-if-changed={}", path.display());
                    let stem = path
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .unwrap_or("icon")
                        .replace(['-', ' ', '.'], "_");
                    let ident = stem.to_ascii_uppercase();

                    if let Err(e) = bake_icon(&path, &ident, &squircle_mask, &mut out_file) {
                        eprintln!("cargo:warning=Failed to bake icon {}: {}", path.display(), e);
                    }
                }
            }
        }
    }

    writeln!(out_file, "}}").unwrap();
}

/// Generates a per-pixel squircle alpha mask for a square icon of `size` pixels,
/// using **4× supersampling** (16 samples per pixel) for smooth, GPU-quality edges.
///
/// Each output pixel integrates 16 uniformly-spaced sub-pixel coverage samples,
/// giving a natural 0–255 alpha ramp that is far smoother than a single-sample
/// distance-field approach. This is the same quality level a vector renderer would
/// produce and eliminates jagged corners on the hardware display.
fn generate_squircle_mask(size: u32) -> Vec<u8> {
    const SUPERSAMPLE: usize = 4; // 4×4 = 16 samples per pixel
    const SAMPLES: f32 = (SUPERSAMPLE * SUPERSAMPLE) as f32;

    let n = size as usize;
    let mut mask = vec![0u8; n * n];

    let half = size as f32 * 0.5;
    let corner_r = SQUIRCLE_RADIUS_RATIO * size as f32;
    let inner = half - corner_r;

    for y in 0..n {
        for x in 0..n {
            let mut coverage = 0.0f32;

            // Jittered grid: sample centres at (k+0.5)/SUPERSAMPLE within the pixel
            for sy in 0..SUPERSAMPLE {
                let sub_y = y as f32 + (sy as f32 + 0.5) / SUPERSAMPLE as f32;
                let dy = (sub_y - half).abs();
                let qy = (dy - inner).max(0.0);

                for sx in 0..SUPERSAMPLE {
                    let sub_x = x as f32 + (sx as f32 + 0.5) / SUPERSAMPLE as f32;
                    let dx = (sub_x - half).abs();
                    let qx = (dx - inner).max(0.0);
                    let dist = (qx * qx + qy * qy).sqrt();

                    // Each sample contributes its fractional coverage (0.0–1.0).
                    // A soft 1-pixel AA band is applied at the squircle boundary so
                    // that partial-coverage sub-pixels blend smoothly.
                    coverage += if dist <= corner_r - 1.0 {
                        1.0
                    } else if dist < corner_r {
                        corner_r - dist // linear ramp over the last 1 sub-pixel
                    } else {
                        0.0
                    };
                }
            }

            mask[y * n + x] = ((coverage / SAMPLES) * 255.0 + 0.5) as u8;
        }
    }

    mask
}

/// Precomputed continuous Bayer 8x8 dither offsets: `(63.5 - BAYER8[i]) / 64.0`.
/// Identical to `pomelo_gfx::color::DITHER_OFFSETS` – duplicated here because
/// build scripts cannot depend on workspace crates directly.
const DITHER_OFFSETS: [f32; 64] = [
    0.9921875, 0.4921875, 0.8671875, 0.3671875, 0.9609375, 0.4609375, 0.8359375, 0.3359375,
    0.2421875, 0.7421875, 0.1171875, 0.6171875, 0.2109375, 0.7109375, 0.0859375, 0.5859375,
    0.8046875, 0.3046875, 0.9296875, 0.4296875, 0.7734375, 0.2734375, 0.8984375, 0.3984375,
    0.0546875, 0.5546875, 0.1796875, 0.6796875, 0.0234375, 0.5234375, 0.1484375, 0.6484375,
    0.9453125, 0.4453125, 0.8203125, 0.3203125, 0.9765625, 0.4765625, 0.8515625, 0.3515625,
    0.1953125, 0.6953125, 0.0703125, 0.5703125, 0.2265625, 0.7265625, 0.1015625, 0.6015625,
    0.7578125, 0.2578125, 0.8828125, 0.3828125, 0.7890625, 0.2890625, 0.9140625, 0.4140625,
    0.0078125, 0.5078125, 0.1328125, 0.6328125, 0.0390625, 0.5390625, 0.1640625, 0.6640625,
];

/// Convert 8-bit RGB to 16-bit RGB565 with Bayer 8×8 ordered dithering at pixel `(x, y)`.
///
/// Subpixel chromatic phase is decorrelated across R, G, B so that each channel
/// samples a different 8×8 tile of the Bayer matrix, dispersing luminance variance
/// and preventing the colour channels from all banding at the same position.
#[inline(always)]
fn dither_rgb888_to_rgb565(r: u8, g: u8, b: u8, x: usize, y: usize) -> u16 {
    let idx_r = ((y & 7) << 3) | (x & 7);
    let idx_g = (((y + 4) & 7) << 3) | ((x + 2) & 7);
    let idx_b = (((y + 2) & 7) << 3) | ((x + 4) & 7);

    let d_r = DITHER_OFFSETS[idx_r];
    let d_g = DITHER_OFFSETS[idx_g];
    let d_b = DITHER_OFFSETS[idx_b];

    // Scale 0-255 → 0-31/63 with the dither offset applied *before* truncation,
    // so the quantisation error is spread across the 8×8 Bayer tile.
    let r5 = ((r as f32 * 0.125 + d_r) as u32).min(31) as u16;
    let g6 = ((g as f32 * 0.250 + d_g) as u32).min(63) as u16;
    let b5 = ((b as f32 * 0.125 + d_b) as u32).min(31) as u16;

    (r5 << 11) | (g6 << 5) | b5
}

fn bake_icon(
    path: &Path,
    ident: &str,
    squircle_mask: &[u8],
    out: &mut File,
) -> Result<(), Box<dyn std::error::Error>> {
    let img = image::open(path)?;
    let rgba = img.to_rgba8();
    let (w, h) = rgba.dimensions();

    // Center square crop
    let crop_size = w.min(h);
    let x_offset = (w - crop_size) / 2;
    let y_offset = (h - crop_size) / 2;

    let cropped =
        image::imageops::crop_imm(&rgba, x_offset, y_offset, crop_size, crop_size).to_image();

    // High quality Lanczos3 resize to ICON_SIZE x ICON_SIZE
    let resized = image::imageops::resize(
        &cropped,
        ICON_SIZE,
        ICON_SIZE,
        image::imageops::FilterType::Lanczos3,
    );

    let total_pixels = (ICON_SIZE * ICON_SIZE) as usize;
    let mut rgb565_array = Vec::with_capacity(total_pixels);
    let mut alpha_array = Vec::with_capacity(total_pixels);

    let stride = ICON_SIZE as usize;
    for (i, pixel) in resized.pixels().enumerate() {
        let r = pixel[0];
        let g = pixel[1];
        let b = pixel[2];
        let img_alpha = pixel[3] as u16;

        // Derive pixel coordinates for the Bayer dither matrix lookup.
        let px = i % stride;
        let py = i / stride;

        // Bayer 8×8 ordered dithering eliminates gradient banding on RGB565 displays.
        let rgb = dither_rgb888_to_rgb565(r, g, b, px, py);

        // Multiply the image's own alpha by the squircle mask alpha.
        // Both are 0-255; the result is kept in 0-255.
        let sq_alpha = squircle_mask[i] as u16;
        let final_alpha = ((img_alpha * sq_alpha) / 255) as u8;

        rgb565_array.push(rgb);
        alpha_array.push(final_alpha);
    }

    // Write Rust static arrays
    writeln!(out, "    pub static {}_RGB: [u16; {}] = [", ident, total_pixels)?;
    for chunk in rgb565_array.chunks(16) {
        write!(out, "       ")?;
        for val in chunk {
            write!(out, " 0x{:04X},", val)?;
        }
        writeln!(out)?;
    }
    writeln!(out, "    ];\n")?;

    writeln!(out, "    pub static {}_ALPHA: [u8; {}] = [", ident, total_pixels)?;
    for chunk in alpha_array.chunks(24) {
        write!(out, "       ")?;
        for val in chunk {
            write!(out, " 0x{:02X},", val)?;
        }
        writeln!(out)?;
    }
    writeln!(out, "    ];\n")?;

    writeln!(
        out,
        "    pub static {}_ICON: BitmapIcon = BitmapIcon {{",
        ident
    )?;
    writeln!(out, "        width: {},", ICON_SIZE)?;
    writeln!(out, "        height: {},", ICON_SIZE)?;
    writeln!(out, "        rgb565: &{}_RGB,", ident)?;
    writeln!(out, "        alpha: &{}_ALPHA,", ident)?;
    writeln!(out, "    }};\n")?;

    Ok(())
}
